[package]
name = "cryptofriends"
version = "0.1.0"
authors = ["Maxb <maxb.personal@gmail.com>"]

[dependencies]
base64 = "0.8.0"
itertools = "0.7.4"
rust-crypto = "0.2"
rand = "0.4"
byteorder = "1.2.3"
